<option disabled selected value="">&mdash; <?php esc_html_e( 'Select field', 'yousync' ); ?> &mdash;</option>
<option value="title"><?php esc_html_e( 'Title', 'yousync' ); ?></option>
<option value="description"><?php esc_html_e( 'Description', 'yousync' ); ?></option>
<option value="thumbnail"><?php esc_html_e( 'Thumbnail', 'yousync' ); ?></option>
<option value="tags"><?php esc_html_e( 'Tags', 'yousync' ); ?></option>
<option value="yousync_category"><?php esc_html_e( 'Video Category', 'yousync' ); ?></option>
<option value="duration"><?php esc_html_e( 'Duration', 'yousync' ); ?></option>
<option value="published_date"><?php esc_html_e( 'Published Date', 'yousync' ); ?></option>
<option value="view_count"><?php esc_html_e( 'View Count', 'yousync' ); ?></option>
<option value="like_count"><?php esc_html_e( 'Like Count', 'yousync' ); ?></option>
<option value="comment_count"><?php esc_html_e( 'Comment Count', 'yousync' ); ?></option>
