<?php
declare(strict_types=1);
/**
 * Channels admin page — top-level WPBuoy Video Sync menu.
 *
 * @package WPBuoyVideoSync
 */

namespace WPBuoyVideoSync;

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Channels_Page Class
 */
class Channels_Page {

	/**
	 * Constructor.
	 */
	public function __construct() {
		add_action( 'admin_menu', array( $this, 'register_menu' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_assets' ) );
		add_action( 'admin_post_wpbuoy_video_sync_save_channels', array( $this, 'save_channels' ) );
		add_action( 'wp_ajax_wpbuoy_video_sync_add_rule', array( $this, 'ajax_add_rule' ) );
		add_action( 'wp_ajax_wpbuoy_video_sync_sync_progress', array( $this, 'ajax_sync_progress' ) );
		add_action( 'wp_ajax_wpbuoy_video_sync_mark_history_read', array( $this, 'ajax_mark_history_read' ) );
		add_action( 'load-toplevel_page_wpbuoy-video-sync',        array( $this, 'add_help_tabs' ) );
		add_action( 'load-wpbuoy_video_sync_page_wpbuoy_video_sync_settings', array( $this, 'add_help_tabs' ) );
	}

	/**
	 * Register contextual Help tabs on every yousync admin screen.
	 *
	 * Generated by docs/skills/create/build/plugin-help-map.py from the live
	 * knowledge base. Article anchors are the section ids the KB theme renders.
	 * Do not hand-edit links here — re-run the script to reconcile.
	 *
	 * @return void
	 */
	public function add_help_tabs() {
		$screen = get_current_screen();
		if ( ! $screen ) {
			return;
		}

		$kb = 'https://wpbuoy.com/yousync/knowledge-base/';

		$screen->add_help_tab( array(
			'id'      => 'yousync-help-getting-started',
			'title'   => __( 'Getting Started', 'wpbuoy-video-sync' ),
			'content' =>
				'<h2>' . esc_html__( 'Getting Started', 'wpbuoy-video-sync' ) . '</h2>' .
				'<ul>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#how-yousync-works' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'How WPBuoy Video Sync works', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#whats-the-difference-between-free-and-pro' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( "What's the difference between Free and Pro?", 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#sync-actions-explained' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Sync actions explained', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#minimum-requirements' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Minimum requirements', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#getting-your-google-api-key' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Getting your Google API key', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#how-to-install' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'How to install', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#initial-configuration' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Initial configuration', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#will-syncing-affect-my-site' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Will syncing affect my site?', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#privacy-and-data-collection' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Privacy and data collection', 'wpbuoy-video-sync' ) . '</a></li>' .
				'</ul>',
		) );

		$screen->add_help_tab( array(
			'id'      => 'yousync-help-connecting-to-youtube',
			'title'   => __( 'Connecting to YouTube', 'wpbuoy-video-sync' ),
			'content' =>
				'<h2>' . esc_html__( 'Connecting to YouTube', 'wpbuoy-video-sync' ) . '</h2>' .
				'<ul>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#how-to-get-a-google-api-key' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'How to get a Google API key', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#api-key-vs-oauth-which-does-yousync-use' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'API key vs OAuth — which does WPBuoy Video Sync use?', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#keeping-your-api-key-secure' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Keeping your API key secure', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#understanding-your-youtube-api-quota' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Understanding your YouTube API quota', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#the-pre-sync-quota-estimate' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'The pre-sync quota estimate', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#conserving-quota' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Conserving quota', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#requesting-a-higher-quota' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Requesting a higher quota', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#fixing-api-key-and-quota-errors' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Fixing API key and quota errors', 'wpbuoy-video-sync' ) . '</a></li>' .
				'</ul>',
		) );

		$screen->add_help_tab( array(
			'id'      => 'yousync-help-features-usage',
			'title'   => __( 'Features & Usage', 'wpbuoy-video-sync' ),
			'content' =>
				'<h2>' . esc_html__( 'Features & Usage', 'wpbuoy-video-sync' ) . '</h2>' .
				'<ul>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#choosing-what-to-import' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Choosing what to import', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#destination-post-type' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Destination post type', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#run-once-vs-recurring-schedules' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Run-once vs recurring schedules', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#thumbnails-and-featured-images' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Thumbnails and featured images', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#sync-history-and-error-logs' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Sync history and error logs', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#the-post-metabox-and-copy-buttons' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'The post metabox and copy buttons', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#post-meta-reference' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Post meta reference', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#compatibility' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Compatibility', 'wpbuoy-video-sync' ) . '</a></li>' .
				'</ul>',
		) );

		$screen->add_help_tab( array(
			'id'      => 'yousync-help-troubleshooting',
			'title'   => __( 'Troubleshooting', 'wpbuoy-video-sync' ),
			'content' =>
				'<h2>' . esc_html__( 'Troubleshooting', 'wpbuoy-video-sync' ) . '</h2>' .
				'<ul>' .
					'<li><a href="' . esc_url( $kb . 'troubleshooting/#api-key-or-quota-errors' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'API key or quota errors', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'troubleshooting/#the-channel-cant-be-found' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( "The channel can't be found", 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'troubleshooting/#im-seeing-duplicate-posts' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( "I'm seeing duplicate posts", 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'troubleshooting/#i-cant-activate-my-license' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( "I can't activate my license", 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'troubleshooting/#how-to-get-support' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'How to get support', 'wpbuoy-video-sync' ) . '</a></li>' .
				'</ul>',
		) );

		$screen->set_help_sidebar(
			'<p><strong>' . esc_html__( 'For more information:', 'wpbuoy-video-sync' ) . '</strong></p>' .
			'<p><a href="' . esc_url( $kb ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Knowledge Base', 'wpbuoy-video-sync' ) . '</a></p>' .
			'<p><a href="https://wpbuoy.com/my-account/support/" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Support', 'wpbuoy-video-sync' ) . '</a></p>'
		);
	}


	/**
	 * Register the top-level WPBuoy Video Sync menu and submenus.
	 *
	 * @return void
	 */
	public function register_menu() {
		add_menu_page(
			__( 'WPBuoy Video Sync', 'wpbuoy-video-sync' ),
			__( 'WPBuoy Video Sync', 'wpbuoy-video-sync' ),
			'manage_options',
			'wpbuoy-video-sync',
			array( $this, 'render_page' ),
			'dashicons-video-alt3',
			26
		);

		// Replace auto-generated first submenu item.
		add_submenu_page(
			'wpbuoy-video-sync',
			__( 'Channels', 'wpbuoy-video-sync' ),
			__( 'Channels', 'wpbuoy-video-sync' ),
			'manage_options',
			'wpbuoy-video-sync',
			array( $this, 'render_page' )
		);
	}

	/**
	 * Render the Channels page.
	 *
	 * @return void
	 */
	public function render_page() {
		$channel = get_option( 'wpbuoy_video_sync_channel_config', array() );
		if ( ! is_array( $channel ) ) {
			$channel = array();
		}

		// Downgrade safety: if a Pro multi-channel array was left behind, use the
		// first channel. Free only ever reads/writes a single flat channel.
		if ( isset( $channel[0] ) ) {
			$channel = is_array( $channel[0] ) ? $channel[0] : array();
		}

		$ch_errors = get_transient( 'wpbuoy_video_sync_ch_errors_' . get_current_user_id() );
		if ( $ch_errors ) {
			delete_transient( 'wpbuoy_video_sync_ch_errors_' . get_current_user_id() );
		}
		$ch_errors = is_array( $ch_errors ) ? $ch_errors : array();

		$has_api_key = ! empty( get_option( 'wpbuoy_video_sync_api_key', '' ) );

		wpbuoy_video_sync_get_template_part( 'channels', 'page', compact( 'channel', 'ch_errors', 'has_api_key' ) );
	}

	/**
	 * Enqueue assets on the Channels page.
	 *
	 * @param string $hook Current admin page hook suffix.
	 * @return void
	 */
	public function enqueue_assets( $hook ) {
		if ( 'toplevel_page_wpbuoy-video-sync' !== $hook ) {
			return;
		}

		wp_enqueue_style( 'tom-select', WPBUOY_VIDEO_SYNC_PLUGIN_URL . 'assets/vendor/tom-select/tom-select.min.css', array(), '2.4.3' );
		wp_enqueue_style( 'yousync-admin', WPBUOY_VIDEO_SYNC_PLUGIN_URL . 'assets/css/admin.css', array( 'tom-select' ), WPBUOY_VIDEO_SYNC_VERSION );
		wp_enqueue_script( 'tom-select', WPBUOY_VIDEO_SYNC_PLUGIN_URL . 'assets/vendor/tom-select/tom-select.complete.min.js', array(), '2.4.3', true );
		wp_enqueue_script( 'yousync-admin', WPBUOY_VIDEO_SYNC_PLUGIN_URL . 'assets/js/admin.js', array( 'jquery', 'tom-select' ), WPBUOY_VIDEO_SYNC_VERSION, true );

		// Render the sync-rule template with a channel-specific name_prefix placeholder
		// for the JS-inserted rule card.
		$name_prefix = 'channels[{{CHANNEL_INDEX}}][sync_rules]';

		wp_localize_script( 'yousync-admin', 'youSync', array(
			'syncRule' => array(
				'rule' => wpbuoy_video_sync_return_template_part( 'sync-rule', null, array( 'name_prefix' => $name_prefix ) ),
			),
			'isChannelsPage'       => true,
			'ajaxUrl'              => admin_url( 'admin-ajax.php' ),
			'addRuleNonce'         => wp_create_nonce( 'wpbuoy_video_sync_add_rule' ),
			'syncProgressNonce'    => wp_create_nonce( 'wpbuoy_video_sync_sync_progress' ),
			'markHistoryReadNonce' => wp_create_nonce( 'wpbuoy_video_sync_mark_history_read' ),
		) );
	}

	/**
	 * Handle the channels form submission.
	 *
	 * @return void
	 */
	public function save_channels() {
		if ( ! isset( $_POST['wpbuoy_video_sync_channels_nonce'] ) ||
			! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['wpbuoy_video_sync_channels_nonce'] ) ), 'wpbuoy_video_sync_save_channels' ) ) {
			wp_die( esc_html__( 'Security check failed.', 'wpbuoy-video-sync' ) );
		}

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You do not have permission to do this.', 'wpbuoy-video-sync' ) );
		}

		$existing = get_option( 'wpbuoy_video_sync_channel_config', array() );
		if ( ! is_array( $existing ) ) {
			$existing = array();
		}

		// Normalize existing to single-channel format for comparison.
		if ( isset( $existing['youtube_id'] ) ) {
			$old_channels = array( $existing );
		} else {
			$old_channels = is_array( $existing ) ? array_values( $existing ) : array();
		}

		// Free is single-channel — only the first posted channel is processed.
		// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized,WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		$first_channel   = ( isset( $_POST['channels'][0] ) && is_array( $_POST['channels'][0] ) ) ? $_POST['channels'][0] : array();
		$posted_channels = $first_channel ? array( $first_channel ) : array();
		$api_key         = get_option( 'wpbuoy_video_sync_api_key', '' );
		$new_channels    = array();
		$save_errors     = array();

		foreach ( $posted_channels as $ch_index => $ch_data ) {
			$old_ch = isset( $old_channels[ $ch_index ] ) ? $old_channels[ $ch_index ] : array();

			$old_youtube_id = $old_ch['youtube_id'] ?? '';
			$new_youtube_id = isset( $ch_data['youtube_id'] ) ? sanitize_text_field( wp_unslash( $ch_data['youtube_id'] ) ) : '';

			// Accept a channel URL or @handle: resolve anything that isn't already a
			// channel ID. On failure, keep the previous ID and surface the error.
			if ( '' !== $new_youtube_id && ! preg_match( '#^UC[A-Za-z0-9_-]{22}$#', $new_youtube_id ) ) {
				$resolved = ( new YouTube_API( $api_key ) )->resolve_channel_id( $new_youtube_id );
				if ( is_wp_error( $resolved ) ) {
					$save_errors[ $new_youtube_id ] = $resolved->get_error_message();
					$new_youtube_id                 = $old_youtube_id;
				} else {
					$new_youtube_id = $resolved;
				}
			}

			$channel = array(
				'youtube_id'    => $new_youtube_id,
				'channel_title' => $old_ch['channel_title'] ?? '',
			);

			// Preserve existing API-fetched data.
			foreach ( array( 'channel_description', 'subscriber_count', 'video_count', 'profile_picture', 'banner_image', 'etag' ) as $key ) {
				if ( isset( $old_ch[ $key ] ) ) {
					$channel[ $key ] = $old_ch[ $key ];
				}
			}

			// Sync rules. Split the stored rules: Pro-only rules are preserved verbatim
			// (they were never rendered, so the form can't represent them) and re-attached
			// after the free rules, so a prior Pro configuration survives a free save.
			$old_rules           = $old_ch['sync_rules'] ?? array();
			$old_free_rules      = array();
			$preserved_pro_rules = array();
			foreach ( $old_rules as $old_rule ) {
				if ( wpbuoy_video_sync_rule_is_unsupported( $old_rule ) ) {
					$preserved_pro_rules[] = $old_rule;
				} else {
					$old_free_rules[] = $old_rule;
				}
			}
			$old_free_rules = array_values( $old_free_rules );

			if ( isset( $ch_data['sync_rules'] ) && is_array( $ch_data['sync_rules'] ) ) {
				$new_rules = array_values( array_map( 'wpbuoy_video_sync_sanitize_sync_rule', $ch_data['sync_rules'] ) );

				foreach ( $new_rules as $i => &$new_rule ) {
					if ( isset( $old_free_rules[ $i ] ) ) {
						$new_rule['sync_status'] = $old_free_rules[ $i ]['sync_status'] ?? '';
						$new_rule['last_synced'] = $old_free_rules[ $i ]['last_synced'] ?? 0;
						$new_rule['sync_count']  = $old_free_rules[ $i ]['sync_count'] ?? 0;
						$new_rule['sync_errors'] = $old_free_rules[ $i ]['sync_errors'] ?? array();

						$old_schedule = $old_free_rules[ $i ]['schedule'] ?? null;
						if ( $old_schedule === $new_rule['schedule'] && ! empty( $old_free_rules[ $i ]['scheduled_at'] ) ) {
							$new_rule['scheduled_at'] = $old_free_rules[ $i ]['scheduled_at'];
						} else {
							$new_rule['scheduled_at'] = time();
						}
					} else {
						$new_rule['scheduled_at'] = time();
					}
				}
				unset( $new_rule );
				$channel['sync_rules'] = array_merge( $new_rules, $preserved_pro_rules );
			} else {
				$channel['sync_rules'] = $preserved_pro_rules;
			}

			// Per-channel defaults.
			$channel['default_post_type'] = isset( $ch_data['default_post_type'] )
				? sanitize_key( wp_unslash( $ch_data['default_post_type'] ) )
				: '';

			// Auto-fetch channel data via YouTube API if channel ID changed or data is missing.
			if (
				$api_key &&
				$new_youtube_id &&
				(
					$new_youtube_id !== $old_youtube_id ||
					empty( $channel['channel_title'] ) ||
					! isset( $channel['subscriber_count'] )
				)
			) {
				$yt_data = ( new YouTube_API( $api_key ) )->get_channel_data( $new_youtube_id );
				if ( ! is_wp_error( $yt_data ) ) {
					$channel['channel_title']       = $yt_data['channel_title'];
					$channel['channel_description'] = $yt_data['channel_description'];
					$channel['subscriber_count']    = $yt_data['subscriber_count'];
					$channel['video_count']         = $yt_data['video_count'];
					$channel['profile_picture']     = $yt_data['profile_picture'];
					$channel['banner_image']        = $yt_data['banner_image'];
					$channel['etag']                = $yt_data['etag'];
				} else {
					$channel['_api_error'] = $yt_data->get_error_message();
					$save_errors[ $new_youtube_id ] = $channel['_api_error'];
				}
			}

			$new_channels[] = $channel;
		}

		// Keep the managed (first) channel even if its YouTube ID was cleared, as long
		// as it still holds preserved Pro rules; otherwise drop an empty channel.
		// Free is single-channel: any extra Pro channels are not retained.
		$new_channels = array_values( array_filter(
			$new_channels,
			fn( $ch ) => ! empty( $ch['youtube_id'] ) || ! empty( $ch['sync_rules'] )
		) );

		// Persist the single flat channel (Pro rules within it are preserved above).
		update_option( 'wpbuoy_video_sync_channel_config', $new_channels[0] ?? array() );

		// Schedule cron events for the channel's free rules (the scheduler skips
		// preserved Pro rules).
		do_action( 'wpbuoy_video_sync_reschedule_option_channels', $new_channels );

		if ( ! empty( $save_errors ) ) {
			set_transient( 'wpbuoy_video_sync_ch_errors_' . get_current_user_id(), $save_errors, 60 );
		}

		wp_safe_redirect( add_query_arg( 'yousync-channels-updated', '1', admin_url( 'admin.php?page=wpbuoy-video-sync' ) ) );
		exit;
	}

	/**
	 * AJAX handler — save a new sync rule from the wizard and return its accordion HTML.
	 *
	 * @return void
	 */
	public function ajax_add_rule(): void {
		check_ajax_referer( 'wpbuoy_video_sync_add_rule', 'nonce' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( 'forbidden', 403 );
		}

		$ch_index = absint( $_POST['channel_index'] ?? 0 ); // phpcs:ignore WordPress.Security.NonceVerification.Missing

		$raw_rule = isset( $_POST['rule'] ) && is_array( $_POST['rule'] ) // phpcs:ignore WordPress.Security.NonceVerification.Missing
			? wp_unslash( $_POST['rule'] ) // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized,WordPress.Security.NonceVerification.Missing
			: array();

		$rule                  = wpbuoy_video_sync_sanitize_sync_rule( $raw_rule );
		$rule['enabled']       = true; // A rule created via the wizard is active and runs on save.
		$rule['scheduled_at']  = time();
		$rule['sync_status']   = '';
		$rule['last_synced']   = 0;
		$rule['sync_count']    = 0;
		$rule['sync_errors']   = array();

		// Load, normalize, append, save.
		$config   = get_option( 'wpbuoy_video_sync_channel_config', array() );
		$is_single = isset( $config['youtube_id'] );
		$channels = $is_single ? array( $config ) : array_values( (array) $config );

		if ( ! isset( $channels[ $ch_index ] ) ) {
			wp_send_json_error( 'invalid_channel', 400 );
		}

		if ( ! isset( $channels[ $ch_index ]['sync_rules'] ) ) {
			$channels[ $ch_index ]['sync_rules'] = array();
		}
		$channels[ $ch_index ]['sync_rules'][] = $rule;
		$rule_index = array_key_last( $channels[ $ch_index ]['sync_rules'] );

		update_option( 'wpbuoy_video_sync_channel_config', $is_single ? $channels[0] : $channels );
		do_action( 'wpbuoy_video_sync_reschedule_option_channels', $channels );

		// Re-read so the rendered card reflects the scheduler's state — an enabled
		// once rule is marked 'syncing' and runs immediately after this save.
		$fresh          = get_option( 'wpbuoy_video_sync_channel_config', array() );
		$fresh_channels = isset( $fresh['youtube_id'] ) ? array( $fresh ) : array_values( (array) $fresh );
		$render_rule    = $fresh_channels[ $ch_index ]['sync_rules'][ $rule_index ] ?? $rule;

		// Render the accordion card for the new rule.
		$name_prefix = 'channels[' . $ch_index . '][sync_rules]';
		ob_start();
		wpbuoy_video_sync_get_template_part( 'sync-rule', null, array(
			'index'              => $rule_index,
			'rule'               => $render_rule,
			'term_id'            => 0,
			'source_type'        => 'channel',
			'name_prefix'        => $name_prefix,
			'is_option_channel'  => true,
			'option_channel_idx' => $ch_index,
		) );
		$html = ob_get_clean();

		wp_send_json_success( array(
			'rule_index' => $rule_index,
			'html'       => $html,
		) );
	}

	/**
	 * AJAX handler — return sync progress for a rule currently syncing.
	 *
	 * @return void
	 */
	public function ajax_sync_progress(): void {
		check_ajax_referer( 'wpbuoy_video_sync_sync_progress', 'nonce' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( 'forbidden', 403 );
		}

		$ch_index   = absint( $_POST['ch_index'] ?? 0 );
		$rule_index = absint( $_POST['rule_index'] ?? 0 );

		$config   = get_option( 'wpbuoy_video_sync_channel_config', array() );
		$channels = isset( $config['youtube_id'] ) ? array( $config ) : array_values( (array) $config );
		$rule     = $channels[ $ch_index ]['sync_rules'][ $rule_index ] ?? null;

		if ( ! $rule ) {
			wp_send_json_error( 'not_found', 404 );
		}

		$sync_status = $rule['sync_status'] ?? '';

		if ( 'syncing' === $sync_status ) {
			$progress = get_transient( 'wpbuoy_video_sync_prog_' . $ch_index . '_' . $rule_index );
			wp_send_json_success( array(
				'status'  => 'syncing',
				'current' => $progress ? (int) $progress['current'] : 0,
				'total'   => $progress ? (int) $progress['total'] : 0,
			) );
		} else {
			$last_synced  = (int) ( $rule['last_synced'] ?? 0 );
			$progress     = get_transient( 'wpbuoy_video_sync_prog_' . $ch_index . '_' . $rule_index );
			wp_send_json_success( array(
				'status'            => $sync_status ?: 'idle',
				'last_synced'       => $last_synced,
				'last_synced_label' => $last_synced ? wp_date( 'F j, Y g:i A', $last_synced ) : '',
				'enabled'           => (bool) ( $rule['enabled'] ?? true ),
				'synced'            => $progress ? (int) $progress['current'] : 0,
				'total'             => $progress ? (int) $progress['total'] : 0,
			) );
		}
	}

	public function ajax_mark_history_read(): void {
		check_ajax_referer( 'wpbuoy_video_sync_mark_history_read', 'nonce' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( 'forbidden', 403 );
		}

		$youtube_id = sanitize_text_field( wp_unslash( $_POST['youtube_id'] ?? '' ) );
		if ( ! $youtube_id ) {
			wp_send_json_error( 'missing_youtube_id', 400 );
		}

		Sync_History::mark_read( $youtube_id );
		wp_send_json_success();
	}

}

new Channels_Page();
