<?php
declare(strict_types=1);
/**
 * Channels admin page — top-level WPBuoy Video Sync menu.
 *
 * @package WPBuoy_Video_Sync
 */

namespace WPBuoy_Video_Sync;

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Channels_Page Class
 */
class Channels_Page {

	/**
	 * Constructor.
	 */
	public function __construct() {
		add_action( 'admin_menu', array( $this, 'register_menu' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_assets' ) );
		add_action( 'admin_post_wpbyvs_save_channels', array( $this, 'save_channels' ) );
		add_action( 'wp_ajax_wpbyvs_add_rule', array( $this, 'ajax_add_rule' ) );
		add_action( 'wp_ajax_wpbyvs_sync_progress', array( $this, 'ajax_sync_progress' ) );
		add_action( 'wp_ajax_wpbyvs_mark_history_read', array( $this, 'ajax_mark_history_read' ) );
		add_action( 'load-toplevel_page_wpbuoy-video-sync',        array( $this, 'add_help_tabs' ) );
		add_action( 'load-wpbyvs_page_wpbyvs_settings', array( $this, 'add_help_tabs' ) );
	}

	/**
	 * Register contextual Help tabs on every wpbyvs admin screen.
	 *
	 * Generated by docs/skills/create/build/plugin-help-map.py from the live
	 * knowledge base. Article anchors are the section ids the KB theme renders.
	 * Do not hand-edit links here — re-run the script to reconcile.
	 *
	 * @return void
	 */
	public function add_help_tabs() {
		$screen = get_current_screen();
		if ( ! $screen ) {
			return;
		}

		$kb = 'https://wpbuoy.com/video-sync/knowledge-base/';

		$screen->add_help_tab( array(
			'id'      => 'wpbyvs-help-getting-started',
			'title'   => __( 'Getting Started', 'wpbuoy-video-sync' ),
			'content' =>
				'<h2>' . esc_html__( 'Getting Started', 'wpbuoy-video-sync' ) . '</h2>' .
				'<ul>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#how-wpbyvs-works' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'How WPBuoy Video Sync works', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#whats-the-difference-between-free-and-pro' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( "What's the difference between Free and Pro?", 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#sync-actions-explained' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Sync actions explained', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#minimum-requirements' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Minimum requirements', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#getting-your-google-api-key' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Getting your Google API key', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#how-to-install' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'How to install', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#initial-configuration' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Initial configuration', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#will-syncing-affect-my-site' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Will syncing affect my site?', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'getting-started/#privacy-and-data-collection' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Privacy and data collection', 'wpbuoy-video-sync' ) . '</a></li>' .
				'</ul>',
		) );

		$screen->add_help_tab( array(
			'id'      => 'wpbyvs-help-connecting-to-youtube',
			'title'   => __( 'Connecting to YouTube', 'wpbuoy-video-sync' ),
			'content' =>
				'<h2>' . esc_html__( 'Connecting to YouTube', 'wpbuoy-video-sync' ) . '</h2>' .
				'<ul>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#how-to-get-a-google-api-key' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'How to get a Google API key', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#api-key-vs-oauth-which-does-wpbyvs-use' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'API key vs OAuth — which does WPBuoy Video Sync use?', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#keeping-your-api-key-secure' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Keeping your API key secure', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#understanding-your-youtube-api-quota' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Understanding your YouTube API quota', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#the-pre-sync-quota-estimate' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'The pre-sync quota estimate', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#conserving-quota' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Conserving quota', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#requesting-a-higher-quota' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Requesting a higher quota', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'connecting-to-youtube/#fixing-api-key-and-quota-errors' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Fixing API key and quota errors', 'wpbuoy-video-sync' ) . '</a></li>' .
				'</ul>',
		) );

		$screen->add_help_tab( array(
			'id'      => 'wpbyvs-help-features-usage',
			'title'   => __( 'Features & Usage', 'wpbuoy-video-sync' ),
			'content' =>
				'<h2>' . esc_html__( 'Features & Usage', 'wpbuoy-video-sync' ) . '</h2>' .
				'<ul>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#choosing-what-to-import' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Choosing what to import', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#destination-post-type' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Destination post type', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#run-once-vs-recurring-schedules' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Run-once vs recurring schedules', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#thumbnails-and-featured-images' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Thumbnails and featured images', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#sync-history-and-error-logs' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Sync history and error logs', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#the-post-metabox-and-copy-buttons' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'The post metabox and copy buttons', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#post-meta-reference' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Post meta reference', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'features-usage/#compatibility' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Compatibility', 'wpbuoy-video-sync' ) . '</a></li>' .
				'</ul>',
		) );

		$screen->add_help_tab( array(
			'id'      => 'wpbyvs-help-troubleshooting',
			'title'   => __( 'Troubleshooting', 'wpbuoy-video-sync' ),
			'content' =>
				'<h2>' . esc_html__( 'Troubleshooting', 'wpbuoy-video-sync' ) . '</h2>' .
				'<ul>' .
					'<li><a href="' . esc_url( $kb . 'troubleshooting/#api-key-or-quota-errors' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'API key or quota errors', 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'troubleshooting/#the-channel-cant-be-found' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( "The channel can't be found", 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'troubleshooting/#im-seeing-duplicate-posts' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( "I'm seeing duplicate posts", 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'troubleshooting/#i-cant-activate-my-license' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( "I can't activate my license", 'wpbuoy-video-sync' ) . '</a></li>' .
					'<li><a href="' . esc_url( $kb . 'troubleshooting/#how-to-get-support' ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'How to get support', 'wpbuoy-video-sync' ) . '</a></li>' .
				'</ul>',
		) );

		$screen->set_help_sidebar(
			'<p><strong>' . esc_html__( 'For more information:', 'wpbuoy-video-sync' ) . '</strong></p>' .
			'<p><a href="' . esc_url( $kb ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Knowledge Base', 'wpbuoy-video-sync' ) . '</a></p>' .
			'<p><a href="https://wpbuoy.com/my-account/support/" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Support', 'wpbuoy-video-sync' ) . '</a></p>'
		);
	}


	/**
	 * Register the top-level WPBuoy Video Sync menu and submenus.
	 *
	 * @return void
	 */
	public function register_menu() {
		add_menu_page(
			__( 'WPBuoy Video Sync', 'wpbuoy-video-sync' ),
			__( 'Video Sync', 'wpbuoy-video-sync' ),
			'manage_options',
			'wpbuoy-video-sync',
			array( $this, 'render_page' ),
			'dashicons-video-alt3',
			26
		);

		// Replace auto-generated first submenu item.
		add_submenu_page(
			'wpbuoy-video-sync',
			__( 'Channels', 'wpbuoy-video-sync' ),
			__( 'Channels', 'wpbuoy-video-sync' ),
			'manage_options',
			'wpbuoy-video-sync',
			array( $this, 'render_page' )
		);
	}

	/**
	 * Render the Channels page.
	 *
	 * @return void
	 */
	public function render_page() {
		$channel = wpbyvs_get_channel_config();

		$ch_errors = get_transient( 'wpbyvs_ch_errors_' . get_current_user_id() );
		if ( $ch_errors ) {
			delete_transient( 'wpbyvs_ch_errors_' . get_current_user_id() );
		}
		$ch_errors = is_array( $ch_errors ) ? $ch_errors : array();

		$has_api_key = ! empty( get_option( 'wpbyvs_api_key', '' ) );

		wpbyvs_get_template_part( 'channels', 'page', compact( 'channel', 'ch_errors', 'has_api_key' ) );
	}

	/**
	 * Enqueue assets on the Channels page.
	 *
	 * @param string $hook Current admin page hook suffix.
	 * @return void
	 */
	public function enqueue_assets( $hook ) {
		if ( 'toplevel_page_wpbuoy-video-sync' !== $hook ) {
			return;
		}

		wp_enqueue_style( 'tom-select', WPBYVS_PLUGIN_URL . 'assets/vendor/tom-select/tom-select.min.css', array(), '2.4.3' );
		wp_enqueue_style( 'wpbyvs-admin', WPBYVS_PLUGIN_URL . 'assets/css/admin.css', array( 'tom-select' ), WPBYVS_VERSION );
		wp_enqueue_script( 'tom-select', WPBYVS_PLUGIN_URL . 'assets/vendor/tom-select/tom-select.complete.min.js', array(), '2.4.3', true );
		wp_enqueue_script( 'wpbyvs-admin', WPBYVS_PLUGIN_URL . 'assets/js/admin.js', array( 'jquery', 'tom-select' ), WPBYVS_VERSION, true );

		// name_prefix for the JS-inserted rule card. Free manages a single channel.
		$name_prefix = 'channel[sync_rules]';

		wp_localize_script( 'wpbyvs-admin', 'wpbyvs', array(
			'syncRule' => array(
				'rule' => wpbyvs_return_template_part( 'sync-rule', null, array( 'name_prefix' => $name_prefix ) ),
			),
			'isChannelsPage'       => true,
			'ajaxUrl'              => admin_url( 'admin-ajax.php' ),
			'addRuleNonce'         => wp_create_nonce( 'wpbyvs_add_rule' ),
			'syncProgressNonce'    => wp_create_nonce( 'wpbyvs_sync_progress' ),
			'markHistoryReadNonce' => wp_create_nonce( 'wpbyvs_mark_history_read' ),
		) );
	}

	/**
	 * Handle the channels form submission.
	 *
	 * @return void
	 */
	public function save_channels() {
		if ( ! isset( $_POST['wpbyvs_channels_nonce'] ) ||
			! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['wpbyvs_channels_nonce'] ) ), 'wpbyvs_save_channels' ) ) {
			wp_die( esc_html__( 'Security check failed.', 'wpbuoy-video-sync' ) );
		}

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You do not have permission to do this.', 'wpbuoy-video-sync' ) );
		}

		$old_ch  = wpbyvs_get_channel_config();
		$api_key = get_option( 'wpbyvs_api_key', '' );
		$save_errors = array();

		// Free manages a single channel — read the one posted channel object.
		// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized,WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		$ch_data = ( isset( $_POST['channel'] ) && is_array( $_POST['channel'] ) ) ? $_POST['channel'] : array();

		$old_youtube_id = $old_ch['youtube_id'] ?? '';
		$new_youtube_id = isset( $ch_data['youtube_id'] ) ? sanitize_text_field( wp_unslash( $ch_data['youtube_id'] ) ) : '';

		// Accept a channel URL or @handle: resolve anything that isn't already a
		// channel ID. On failure, keep the previous ID and surface the error.
		if ( '' !== $new_youtube_id && ! preg_match( '#^UC[A-Za-z0-9_-]{22}$#', $new_youtube_id ) ) {
			$resolved = ( new YouTube_API( $api_key ) )->resolve_channel_id( $new_youtube_id );
			if ( is_wp_error( $resolved ) ) {
				$save_errors[ $new_youtube_id ] = $resolved->get_error_message();
				$new_youtube_id                 = $old_youtube_id;
			} else {
				$new_youtube_id = $resolved;
			}
		}

		$channel = array(
			'youtube_id'    => $new_youtube_id,
			'channel_title' => $old_ch['channel_title'] ?? '',
		);

		// Preserve existing API-fetched data.
		foreach ( array( 'channel_description', 'subscriber_count', 'video_count', 'profile_picture', 'banner_image', 'etag' ) as $key ) {
			if ( isset( $old_ch[ $key ] ) ) {
				$channel[ $key ] = $old_ch[ $key ];
			}
		}

		// Sync rules — sanitize the posted rules to free shape, carrying per-rule runtime
		// state (status, counts, errors, scheduled_at) from the matching stored rule.
		$old_rules = array_values( $old_ch['sync_rules'] ?? array() );
		if ( isset( $ch_data['sync_rules'] ) && is_array( $ch_data['sync_rules'] ) ) {
			$new_rules = array_values( array_map( 'wpbyvs_sanitize_sync_rule', $ch_data['sync_rules'] ) );

			foreach ( $new_rules as $i => &$new_rule ) {
				if ( isset( $old_rules[ $i ] ) ) {
					$new_rule['sync_status'] = $old_rules[ $i ]['sync_status'] ?? '';
					$new_rule['last_synced'] = $old_rules[ $i ]['last_synced'] ?? 0;
					$new_rule['sync_count']  = $old_rules[ $i ]['sync_count'] ?? 0;
					$new_rule['sync_errors'] = $old_rules[ $i ]['sync_errors'] ?? array();
					$new_rule['scheduled_at'] = ! empty( $old_rules[ $i ]['scheduled_at'] ) ? $old_rules[ $i ]['scheduled_at'] : time();
				} else {
					$new_rule['scheduled_at'] = time();
				}
			}
			unset( $new_rule );
			$channel['sync_rules'] = $new_rules;
		} else {
			$channel['sync_rules'] = array();
		}

		// Per-channel default destination post type.
		$channel['default_post_type'] = isset( $ch_data['default_post_type'] )
			? sanitize_key( wp_unslash( $ch_data['default_post_type'] ) )
			: '';

		// Auto-fetch channel data via YouTube API if channel ID changed or data is missing.
		if (
			$api_key &&
			$new_youtube_id &&
			(
				$new_youtube_id !== $old_youtube_id ||
				empty( $channel['channel_title'] ) ||
				! isset( $channel['subscriber_count'] )
			)
		) {
			$yt_data = ( new YouTube_API( $api_key ) )->get_channel_data( $new_youtube_id );
			if ( ! is_wp_error( $yt_data ) ) {
				$channel['channel_title']       = $yt_data['channel_title'];
				$channel['channel_description'] = $yt_data['channel_description'];
				$channel['subscriber_count']    = $yt_data['subscriber_count'];
				$channel['video_count']         = $yt_data['video_count'];
				$channel['profile_picture']     = $yt_data['profile_picture'];
				$channel['banner_image']        = $yt_data['banner_image'];
				$channel['etag']                = $yt_data['etag'];
			} else {
				$channel['_api_error'] = $yt_data->get_error_message();
				$save_errors[ $new_youtube_id ] = $channel['_api_error'];
			}
		}

		// Drop an empty channel (no ID and no rules).
		if ( empty( $channel['youtube_id'] ) && empty( $channel['sync_rules'] ) ) {
			$channel = array();
		}

		// Persist the single flat channel.
		update_option( 'wpbyvs_channel_config', $channel );

		// Schedule cron events for the channel's rules.
		do_action( 'wpbyvs_reschedule_option_channels' );

		if ( ! empty( $save_errors ) ) {
			set_transient( 'wpbyvs_ch_errors_' . get_current_user_id(), $save_errors, 60 );
		}

		wp_safe_redirect( add_query_arg( 'wpbyvs-channels-updated', '1', admin_url( 'admin.php?page=wpbuoy-video-sync' ) ) );
		exit;
	}

	/**
	 * AJAX handler — save a new sync rule from the wizard and return its accordion HTML.
	 *
	 * @return void
	 */
	public function ajax_add_rule(): void {
		check_ajax_referer( 'wpbyvs_add_rule', 'nonce' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( 'forbidden', 403 );
		}

		$raw_rule = isset( $_POST['rule'] ) && is_array( $_POST['rule'] ) // phpcs:ignore WordPress.Security.NonceVerification.Missing
			? wp_unslash( $_POST['rule'] ) // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized,WordPress.Security.NonceVerification.Missing
			: array();

		$rule                  = wpbyvs_sanitize_sync_rule( $raw_rule );
		$rule['enabled']       = true; // A rule created via the wizard is active and runs on save.
		$rule['scheduled_at']  = time();
		$rule['sync_status']   = '';
		$rule['last_synced']   = 0;
		$rule['sync_count']    = 0;
		$rule['sync_errors']   = array();

		// Load the single channel, append, save.
		$channel = wpbyvs_get_channel_config();
		if ( empty( $channel['youtube_id'] ) ) {
			wp_send_json_error( 'invalid_channel', 400 );
		}
		if ( ! isset( $channel['sync_rules'] ) || ! is_array( $channel['sync_rules'] ) ) {
			$channel['sync_rules'] = array();
		}
		$channel['sync_rules'][] = $rule;
		$rule_index = array_key_last( $channel['sync_rules'] );

		update_option( 'wpbyvs_channel_config', $channel );
		do_action( 'wpbyvs_reschedule_option_channels' );

		// Re-read so the rendered card reflects the scheduler's state — an enabled
		// once rule is marked 'syncing' and runs immediately after this save.
		$fresh       = wpbyvs_get_channel_config();
		$render_rule = $fresh['sync_rules'][ $rule_index ] ?? $rule;

		// Render the accordion card for the new rule.
		$name_prefix = 'channel[sync_rules]';
		ob_start();
		wpbyvs_get_template_part( 'sync-rule', null, array(
			'index'             => $rule_index,
			'rule'              => $render_rule,
			'term_id'           => 0,
			'source_type'       => 'channel',
			'name_prefix'       => $name_prefix,
			'is_option_channel' => true,
		) );
		$html = ob_get_clean();

		wp_send_json_success( array(
			'rule_index' => $rule_index,
			'html'       => $html,
		) );
	}

	/**
	 * AJAX handler — return sync progress for a rule currently syncing.
	 *
	 * @return void
	 */
	public function ajax_sync_progress(): void {
		check_ajax_referer( 'wpbyvs_sync_progress', 'nonce' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( 'forbidden', 403 );
		}

		$rule_index = absint( $_POST['rule_index'] ?? 0 );

		$channel = wpbyvs_get_channel_config();
		$rule    = $channel['sync_rules'][ $rule_index ] ?? null;

		if ( ! $rule ) {
			wp_send_json_error( 'not_found', 404 );
		}

		$sync_status = $rule['sync_status'] ?? '';

		if ( 'syncing' === $sync_status ) {
			$progress = get_transient( 'wpbyvs_prog_' . $rule_index );
			wp_send_json_success( array(
				'status'  => 'syncing',
				'current' => $progress ? (int) $progress['current'] : 0,
				'total'   => $progress ? (int) $progress['total'] : 0,
			) );
		} else {
			$last_synced  = (int) ( $rule['last_synced'] ?? 0 );
			$progress     = get_transient( 'wpbyvs_prog_' . $rule_index );
			wp_send_json_success( array(
				'status'            => $sync_status ?: 'idle',
				'last_synced'       => $last_synced,
				'last_synced_label' => $last_synced ? wp_date( 'F j, Y g:i A', $last_synced ) : '',
				'enabled'           => (bool) ( $rule['enabled'] ?? true ),
				'synced'            => $progress ? (int) $progress['current'] : 0,
				'total'             => $progress ? (int) $progress['total'] : 0,
			) );
		}
	}

	public function ajax_mark_history_read(): void {
		check_ajax_referer( 'wpbyvs_mark_history_read', 'nonce' );

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( 'forbidden', 403 );
		}

		$youtube_id = sanitize_text_field( wp_unslash( $_POST['youtube_id'] ?? '' ) );
		if ( ! $youtube_id ) {
			wp_send_json_error( 'missing_youtube_id', 400 );
		}

		Sync_History::mark_read( $youtube_id );
		wp_send_json_success();
	}

}

new Channels_Page();
